export const RECEIVE_SEARCHED_BOOKS = "RECEIVE SEARCH RESULTS";
export const RECEIVE_MY_BOOKS = "RECEIVE MY BOOKS";
export const ADD_TO_MY_LIST = "ADD SEARCH BOOK TO ONE OF MY LISTS";
export const UPDATE_MY_LIST = "UPDATE TO READ AND HAVE READ LISTS"
export const DELETE_SEARCH_BOOK = "DELETE SEARCH BOOK";

export const HANDLE_SUCCESS = "HANDLE SUCCESS";
export const RESET_ERROR = "RESET ERROR";

export const HANDLE_GET_ERROR = "HANDLE GET LISTS ERROR";
export const HANDLE_ADD_TWICE_ERROR = "HANDLE ADD TWICE ERROR";
export const HANDLE_UPDATE_ERROR = "HANDLE UPDATE ERROR";
export const HANDLE_DELETE_ERROR = "HANDLE DELETE ERROR";
export const HANDLE_API_ERROR = "HANDLE API ERROR";
export const HANDLE_SEARCH_DISPLAY_ERROR = "HANDLE SEARCH DISPLAY ERROR";
