export const RECEIVE_SEARCHED_BOOKS = "RECEIVE SEARCH RESULTS";
export const RECEIVE_MY_BOOKS = "RECEIVE MY BOOKS";
export const ADD_TO_MY_LIST = "ADD SEARCH BOOK TO ONE OF MY LISTS";
export const UPDATE_MY_LIST = "UPDATE TO READ AND HAVE READ LISTS"
export const DELETE_SEARCH_BOOK = "DELETE SEARCH BOOK";
